"""
Agent State Definition
Defines the state structure for the LangGraph agent.
"""

from typing import TypedDict, List, Dict, Any, Optional
from typing_extensions import Annotated
from langgraph.graph import add_messages


class AgentState(TypedDict):
    """
    State for the LangGraph agent.
    
    Attributes:
        messages: Conversation history (managed by add_messages)
        query: Current user query
        search_results: Results from semantic search
        generated_text: Text generated by the writing node
        next_action: Next action to take (search, write, or end)
        context: Additional context for generation
    """
    messages: Annotated[List[Dict[str, str]], add_messages]
    query: str
    search_results: Optional[List[Dict[str, Any]]]
    generated_text: Optional[str]
    next_action: str
    context: Optional[str]
